# Generated by Django 4.0.6 on 2023-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_api', '0002_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
